[package]
name = "projektna_prog_2"
version = "0.1.0"
edition = "2021"

[dependencies]

rand = "0.8"
[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image", "ttf"]


[[bin]]
name = "sdl2_app"
path = "src/bin/sdl2_app/main.rs"
